rtspAddress: 127.0.0.1:8554
rtspTransports: [tcp]
rtmpAddress: :1935
hls: no
webrtc: yes
webrtcAddress: :8889
webrtcLocalUDPAddress: :8189
webrtcLocalTCPAddress: ""
srt: no

authMethod: internal
authInternalUsers:
  - user: publisher
    pass: replace-with-strong-password
    ips: []
    permissions:
      - action: publish
        path: "~^live/.+$"
  - user: any
    pass:
    ips: ["127.0.0.1", "::1"]
    permissions:
      - action: read
        path: "~^live/.+$"
      - action: api
      - action: metrics
      - action: pprof

paths:
  all_others:
    source: publisher
